name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache uv cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install uv and set Python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-extras --dev

      # - name: Run lint
      #   run: uv run ruff check .

      - name: Run tests
        run: uv run pytest tests

      - name: Build package
        run: uv build

      - name: Publish package
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: uv publish --token ${{ secrets.PYPI_API_TOKEN }}
